#!/bin/sh
# /etc/grub.d/40_flash   18.
exec tail -n +6 $0

default='Windows';timeout=5

submenu 'Windows' --class windows --class os {
   src='/EFI/Microsoft/Boot/bootmgfw.efi'; root='x'
   if [ ${grub_platform} = efi ]
     then   avload='chainloader'; insmod part_gpt; insmod fat; search -n -s -f ${src}
      if [ ${root} = x ]; then src='/bootmgr.efi'; search -n -s -f ${src}; fi
     else   avload='ntldr'; insmod part_msdos; insmod ntfs; search -n -s -f ${src}
      if [ ${root} = x ]
        then   src='/bootmgr'; search -n -s -f ${src}
         if [ ${root} = x ]
           then   src='/ntldr'; search -n -s -f ${src}
            if [ ${root} = x ]
              then   src='/MSDOS.SYS'; insmod fat; search -n -s -f ${src}
               if [ ${root} = x ]
                 then   src='/I386/SETUPLDR.BIN'
               #   insmod   iso9660
               #   insmod   udf
                  search -n -s -f ${src}
                  if [ ${root} = x ]
                    then   src='/BCDW/LOADER.BIN'; search -n -s -f ${src}
                     if [ ${root} = x ]
                       then   src='/opt/avndos.img'; search -n -s -f ${src}
                        if [ ${root} = x ]
                          then   src='Windows'
                          else   avinit="initrd16 $src"; avload='linux16'; src='/boot/syslinux/memdisk ima raw'
                        fi
                     fi
                  fi
                 else   src='+1'; drivemap -s (hd0) ${root}
               fi
            fi
         fi
      fi
      if [ "${src}" = "+1" ]; then avload='chainloader'; else insmod ${avload}; fi
   fi
   if [ ${root} = x ]
     then   msg="$src not exist!"; avload=''; avinit=''
     else   msg="Load $src from $root"
   fi
   #echo "$msg"; sleep -v 0
   if [ -n "${avload}" ]; then ${avload} ${src}; fi
   if [ -n "${avinit}" ]; then ${avinit}; fi

}